# Generated by Django 5.2.8 on 2025-11-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0005_merge_20241120_0000'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagetemplate',
            new_name='templates_a_organiz_8e2b87_idx',
            old_name='template_default_idx',
        ),
    ]
