# Generated by Django 5.2.8 on 2025-11-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_organiz_b709e0_idx',
            old_name='notifications_org_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_organiz_699081_idx',
            old_name='notifications_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_organiz_b31df3_idx',
            old_name='notifications_org_sev_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecipient',
            new_name='notificatio_organiz_ce340d_idx',
            old_name='notirec_org_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationrecipient',
            new_name='notificatio_organiz_ea196b_idx',
            old_name='notirec_org_user_read2_idx',
        ),
    ]
