# Generated by Django 5.2.8 on 2025-11-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='billinglog',
            new_name='billing_bil_organiz_2f9400_idx',
            old_name='billinglog_organiza_621753_idx',
        ),
        migrations.RenameIndex(
            model_name='billinglog',
            new_name='billing_bil_request_7ffea3_idx',
            old_name='billinglog_request_79b6e5_idx',
        ),
        migrations.AlterField(
            model_name='billinglog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
