# Generated by Django 5.2.8 on 2025-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_whatsapp_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
