# Generated by Django 5.2.8 on 2025-11-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_scoped_unique_identifiers'),
        ('organizations', '0004_userprofile_display_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='uniq_contact_email_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='uniq_contact_whatsapp_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='uniq_contact_telegram_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='uniq_contact_instagram_scoped_per_org',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='uniq_contact_instagram_user_per_org',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', True), _negated=True), fields=('organization', 'email'), name='uniq_contact_email_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_whatsapp__isnull', True), _negated=True), fields=('organization', 'phone_whatsapp'), name='uniq_contact_whatsapp_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_chat_id__isnull', True), _negated=True), fields=('organization', 'telegram_chat_id'), name='uniq_contact_telegram_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_scoped_id__isnull', True), _negated=True), fields=('organization', 'instagram_scoped_id'), name='uniq_contact_instagram_scoped_per_org'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_user_id__isnull', True), _negated=True), fields=('organization', 'instagram_user_id'), name='uniq_contact_instagram_user_per_org'),
        ),
    ]
