# Generated by Django 5.2.8 on 2025-11-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0014_telegram_invite_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegraminvitetoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
