# Generated by Django 5.2.8 on 2025-11-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0017_whatsapp_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrammessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
