# Generated by Django 5.2.8 on 2025-11-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0022_emailjob_campaign_emailrecipient_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailrecipient',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('read', 'Read')], default='queued', max_length=20),
        ),
    ]
